#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 35.227.47.184:80 check
        server web2 35.190.188.208:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start

#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 338094-web-01 100.25.165.72:80
        server 338094-web-02 34.203.29.217:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart